truncate table ITIMAM.bp_previous immediate;
insert into ITIMAM.bp_previous select * from ITIMAM.bp_current;
truncate table ITIMAM.bp_current immediate;

CALL SYSPROC.ADMIN_CMD ('RUNSTATS ON TABLE ITIMAM.BP_PREVIOUS ON ALL COLUMNS AND INDEXES ALL ALLOW WRITE ACCESS');
--CALL SYSPROC.ADMIN_CMD ('REORG INDEXES ALL FOR TABLE ITIMAM.BP_PREVIOUS ALLOW READ ACCESS');
--CALL SYSPROC.ADMIN_CMD ('REORG TABLE ITIMAM.BP_PREVIOUS ALLOW READ ACCESS');

		